// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PrviLabos.DAL;

#nullable disable

namespace PrviLabos.DAL.Migrations
{
    [DbContext(typeof(PrviLabosDbContext))]
    [Migration("20260521163000_AddSoftDeleteToAgentsAndTickets")]
    partial class AddSoftDeleteToAgentsAndTickets
    {
    }
}
